language: csharp
dist: trusty
mono: none
dotnet: 2.0.0
install:
- dotnet restore
script:
- dotnet build
- dotnet test TOIFeedRepo.Tests/TOIFeedRepo.Tests.csproj
- dotnet test TOIFeedServer.Tests/TOIFeedServer.Tests.csproj
- dotnet test TOIMobileClient.Tests/TOIMobileClient.Tests.csproj
- dotnet test TOIWebClient.Tests/TOIWebClient.Tests.csproj