// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TOIFeedServer.Database;
using TOIFeedServer.Models;

namespace TOIFeedServer.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20171113132539_toi")]
    partial class toi
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("TOIFeedServer.Models.ContextModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(70);

                    b.HasKey("Id");

                    b.ToTable("Contexts");
                });

            modelBuilder.Entity("TOIFeedServer.Models.TagModel", b =>
                {
                    b.Property<string>("TagId")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<string>("Name");

                    b.Property<int>("Radius");

                    b.Property<int>("TagType");

                    b.HasKey("TagId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("TOIFeedServer.Models.ToiModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Image");

                    b.Property<string>("Title");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("Tois");
                });

            modelBuilder.Entity("TOIFeedServer.Models.ToiModel+StringId", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ToiModelId");

                    b.Property<string>("ToiModelId1");

                    b.Property<string>("Value");

                    b.HasKey("Key");

                    b.HasIndex("ToiModelId");

                    b.HasIndex("ToiModelId1");

                    b.ToTable("StringId");
                });

            modelBuilder.Entity("TOIFeedServer.Models.ToiModel+StringId", b =>
                {
                    b.HasOne("TOIFeedServer.Models.ToiModel")
                        .WithMany("Contexts")
                        .HasForeignKey("ToiModelId");

                    b.HasOne("TOIFeedServer.Models.ToiModel")
                        .WithMany("Tags")
                        .HasForeignKey("ToiModelId1");
                });
#pragma warning restore 612, 618
        }
    }
}
