// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;
using TOIFeedServer;

namespace TOIFeedServer.Migrations
{
    [DbContext(typeof(ToiModelContext))]
    [Migration("20171016123930_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("TOIFeedServer.TestFk", b =>
                {
                    b.Property<int>("Id");

                    b.HasKey("Id");

                    b.ToTable("testFK");
                });

            modelBuilder.Entity("TOIFeedServer.ToiModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("Tois");
                });

            modelBuilder.Entity("TOIFeedServer.TestFk", b =>
                {
                    b.HasOne("TOIFeedServer.ToiModel", "ToiModel")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
