// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TOIFeedServer.Database;
using TOIFeedServer.Models;

namespace TOIFeedServer.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("TOIFeedServer.Models.ContextModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(70);

                    b.Property<Guid?>("ToiModelId");

                    b.HasKey("Id");

                    b.HasIndex("ToiModelId");

                    b.ToTable("Contexts");
                });

            modelBuilder.Entity("TOIFeedServer.Models.TagModel", b =>
                {
                    b.Property<Guid>("TagId")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<string>("Name");

                    b.Property<int>("Radius");

                    b.Property<int>("TagType");

                    b.Property<Guid?>("ToiModelId");

                    b.HasKey("TagId");

                    b.HasIndex("ToiModelId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("TOIFeedServer.Models.ToiModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Image");

                    b.Property<string>("Title");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("Tois");
                });

            modelBuilder.Entity("TOIFeedServer.Models.ContextModel", b =>
                {
                    b.HasOne("TOIFeedServer.Models.ToiModel")
                        .WithMany("ContextModels")
                        .HasForeignKey("ToiModelId");
                });

            modelBuilder.Entity("TOIFeedServer.Models.TagModel", b =>
                {
                    b.HasOne("TOIFeedServer.Models.ToiModel")
                        .WithMany("TagModels")
                        .HasForeignKey("ToiModelId");
                });
#pragma warning restore 612, 618
        }
    }
}
